/*
 * pcm1808_test — validates the PCM1808 ADC by capturing audio over I2S
 * and streaming it as a WAV file over UART for host analysis.
 *
 * Workflow:
 *   1. Wire PCM1808 module to Pico 2 (see wiring table below)
 *   2. Flash pcm1808_test.uf2
 *   3. Run: python3 tools/capture_wav.py /dev/cu.usbmodem* --guitar pcm1808 --duration 5
 *   4. Validate: check output WAV in Audacity — strum guitar and confirm signal
 *
 * PCM1808 module wiring:
 *   PCM1808 VCC  (5V)  → Pico VBUS (pin 40)
 *   PCM1808 GND        → Pico GND
 *   PCM1808 SCKI       → GPIO 21  (12.288 MHz clock output via GPOUT0)
 *   PCM1808 BCK        → GPIO 2   (3.072 MHz bit clock, generated by PIO)
 *   PCM1808 LRCK       → GPIO 3   (48 kHz L/R clock, generated by PIO)
 *   PCM1808 DOUT       → GPIO 4   (I2S data to Pico)
 *   PCM1808 MD0        → GND      (slave mode)
 *   PCM1808 MD1        → GND      (slave mode)
 *   PCM1808 FMT        → 3.3V     (left-justified format, matches this PIO driver)
 *   PCM1808 VINL       → TL072 SOUT (guitar signal, AC-coupled)
 *   PCM1808 VINR       → GND or NC
 *
 * Note: if your module has MD0/MD1/FMT already strapped on the PCB (common on
 * cheap breakouts), check the silkscreen — they may not need external wiring.
 *
 * Output:
 *   Left-channel audio only is streamed as 16-bit mono 48 kHz WAV over UART.
 *   The capture duration is set by CAPTURE_SECONDS below.
 */

#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/dma.h"
#include "hardware/clocks.h"
#include "i2s/i2s_in.pio.h"

#include <cstdio>
#include <cstring>
#include <cmath>

// ---------------------------------------------------------------------------
// GPIO assignments
// ---------------------------------------------------------------------------
#define I2S_IN_BCK_PIN   2    // BCK output; LRCK = BCK_PIN + 1 = GPIO 3
#define I2S_IN_DATA_PIN  4    // DOUT input from PCM1808
#define SCKI_PIN         21   // System clock output to PCM1808 (GPOUT0)

// ---------------------------------------------------------------------------
// Audio parameters
// ---------------------------------------------------------------------------
static constexpr uint32_t SAMPLE_RATE     = 48000;
static constexpr uint32_t CAPTURE_SECONDS = 5;
static constexpr uint32_t CAPTURE_SAMPLES = SAMPLE_RATE * CAPTURE_SECONDS;  // mono samples

// ---------------------------------------------------------------------------
// Capture buffer — stereo int32 words from PIO, left channel only extracted
// ---------------------------------------------------------------------------
// PIO produces interleaved L/R int32 pairs.  We capture into a stereo buffer
// then extract the left channel for the WAV output.
static int32_t  stereo_buf[CAPTURE_SAMPLES * 2];   // L,R pairs
static int16_t  pcm_out[CAPTURE_SAMPLES];          // 16-bit mono output

// ---------------------------------------------------------------------------
// Raw byte output (same pattern as offline_test — avoids newline translation)
// ---------------------------------------------------------------------------
static void write_bytes(const void *buf, uint32_t len) {
    const uint8_t *p = static_cast<const uint8_t *>(buf);
    for (uint32_t i = 0; i < len; i++) putchar_raw(p[i]);
}
static void write_u16_le(uint16_t v) {
    uint8_t b[2] = { uint8_t(v), uint8_t(v >> 8) };
    write_bytes(b, 2);
}
static void write_u32_le(uint32_t v) {
    uint8_t b[4] = { uint8_t(v), uint8_t(v>>8), uint8_t(v>>16), uint8_t(v>>24) };
    write_bytes(b, 4);
}

// ---------------------------------------------------------------------------

int main() {
    stdio_init_all();

    // Wait for host before starting (same handshake as offline_test)
    while (true) {
        printf("READY\n");
        fflush(stdout);
        int c = getchar_timeout_us(1000000);
        if (c != PICO_ERROR_TIMEOUT) break;
    }

    printf("PCM1808 test — %u samples @ %u Hz (%u sec)\n",
           CAPTURE_SAMPLES, SAMPLE_RATE, CAPTURE_SECONDS);
    fflush(stdout);

    // ---- SCKI: route sys_clk / 12.207 ≈ 12.288 MHz to GPIO 21 via GPOUT0 ----
    // 150 MHz / 12.207 ≈ 12.288 MHz = 256 × 48 kHz (PCM1808 auto-detects 256fs)
    clock_gpio_init(SCKI_PIN, CLOCKS_CLK_GPOUT0_CTRL_AUXSRC_VALUE_CLK_SYS, 12.207f);

    // ---- PIO I2S input setup ----
    PIO  pio    = pio1;           // pio0 SM0 is reserved for I2S output in main firmware
    uint sm     = 0;
    uint offset = pio_add_program(pio, &i2s_in_program);

    pio_sm_config c = i2s_in_program_get_default_config(offset);

    // in pin = DOUT (DATA_PIN); side-set pins = BCK, LRCK (BCK_PIN, BCK_PIN+1)
    sm_config_set_in_pins(&c, I2S_IN_DATA_PIN);
    sm_config_set_sideset_pins(&c, I2S_IN_BCK_PIN);

    // Shift LEFT, autopush at 32 bits — first received bit ends up at ISR[31] (MSB)
    sm_config_set_in_shift(&c, false, true, 32);

    // Join FIFOs for deeper RX buffer
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);

    // PIO clock = 2 × BCK = 2 × (48000 × 64) = 6.144 MHz
    float div = (float)clock_get_hz(clk_sys) / (2.0f * SAMPLE_RATE * 64.0f);
    sm_config_set_clkdiv(&c, div);

    // Configure GPIO directions: BCK and LRCK as outputs, DOUT as input
    pio_gpio_init(pio, I2S_IN_BCK_PIN);
    pio_gpio_init(pio, I2S_IN_BCK_PIN + 1);
    pio_gpio_init(pio, I2S_IN_DATA_PIN);
    pio_sm_set_consecutive_pindirs(pio, sm, I2S_IN_BCK_PIN,  2, true);   // BCK, LRCK out
    pio_sm_set_consecutive_pindirs(pio, sm, I2S_IN_DATA_PIN, 1, false);  // DOUT in

    pio_sm_init(pio, sm, offset + i2s_in_offset_entry_point, &c);

    // ---- DMA: PIO RX FIFO → stereo_buf ----
    int dma_chan = dma_claim_unused_channel(true);
    dma_channel_config dc = dma_channel_get_default_config(dma_chan);
    channel_config_set_transfer_data_size(&dc, DMA_SIZE_32);
    channel_config_set_read_increment(&dc, false);
    channel_config_set_write_increment(&dc, true);
    channel_config_set_dreq(&dc, pio_get_dreq(pio, sm, false));  // false = RX
    dma_channel_configure(dma_chan, &dc,
        stereo_buf,                        // write to capture buffer
        &pio->rxf[sm],                     // read from PIO RX FIFO
        CAPTURE_SAMPLES * 2,               // stereo: 2 words per sample
        false);                            // don't start yet

    printf("Capturing %u seconds — strum the guitar now...\n", CAPTURE_SECONDS);
    fflush(stdout);

    // Start PIO then DMA
    pio_sm_set_enabled(pio, sm, true);
    dma_channel_start(dma_chan);

    // Wait for capture to complete
    dma_channel_wait_for_finish_blocking(dma_chan);
    pio_sm_set_enabled(pio, sm, false);

    printf("Capture done. Processing...\n");
    fflush(stdout);

    // ---- Extract left channel, convert 24-bit int32 → 16-bit int16 ----
    // PIO ISR shift-left: word[31:8] = 24-bit audio (MSB at bit 31), word[7:0] = 0 padding
    // Stereo layout: stereo_buf[2i] = left, stereo_buf[2i+1] = right
    int32_t  peak   = 0;
    int64_t  sum_sq = 0;

    for (uint32_t i = 0; i < CAPTURE_SAMPLES; i++) {
        int32_t raw  = stereo_buf[i * 2];          // left channel
        int32_t s24  = raw >> 8;                   // signed 24-bit in int32
        int16_t s16  = (int16_t)(s24 >> 8);        // scale to 16-bit
        pcm_out[i]   = s16;
        int32_t abs_s = s24 < 0 ? -s24 : s24;
        if (abs_s > peak) peak = abs_s;
        sum_sq += (int64_t)s16 * s16;
    }

    float rms = sqrtf((float)sum_sq / CAPTURE_SAMPLES);
    printf("Peak: %ld  RMS: %.1f  (16-bit scale)\n", (long)peak, rms);

    if (rms < 50.0f) {
        printf("WARNING: very low signal — check connections and gain setting\n");
    } else {
        printf("Signal detected OK\n");
    }
    fflush(stdout);

    // ---- Stream 16-bit mono WAV over UART ----
    const uint32_t data_bytes = CAPTURE_SAMPLES * sizeof(int16_t);

    printf("WAV_DATA_START\n");
    fflush(stdout);

    write_bytes("RIFF", 4);
    write_u32_le(36 + data_bytes);
    write_bytes("WAVE", 4);
    write_bytes("fmt ", 4);
    write_u32_le(16);
    write_u16_le(1);                        // PCM
    write_u16_le(1);                        // mono
    write_u32_le(SAMPLE_RATE);
    write_u32_le(SAMPLE_RATE * 2);
    write_u16_le(2);
    write_u16_le(16);
    write_bytes("data", 4);
    write_u32_le(data_bytes);
    write_bytes(pcm_out, data_bytes);

    printf("\nWAV_DATA_END\n");
    fflush(stdout);

    while (true) tight_loop_contents();
}