/*
 * pcm1808_test — validates the PCM1808 ADC by capturing 1 second of I2S audio
 * to RAM, then streaming it as a WAV file over UART.
 *
 * Capture-then-stream avoids the UART bandwidth problem: UART at 115200 is
 * ~11 KB/s but live audio is 96 KB/s.  A 1-second stereo int32 buffer (384 KB)
 * fits comfortably in the RP2350's 520 KB SRAM.
 *
 * Workflow:
 *   1. Wire PCM1808 module to Pico 2 (see wiring table below)
 *   2. Flash pcm1808_test.uf2
 *   3. Run: python3 tools/capture_wav.py /dev/cu.usbmodem* --guitar pcm1808 --duration 1
 *   4. Strum the guitar during the "Capturing" message — hold a chord for the full second
 *   5. Check output WAV in Audacity — confirm signal present
 *
 * PCM1808 module wiring:
 *   PCM1808 VCC  (5V)  → Pico VBUS (pin 40)
 *   PCM1808 GND        → Pico GND
 *   PCM1808 SCKI       → GPIO 21  (12.288 MHz clock output via GPOUT0)
 *   PCM1808 BCK        → GPIO 2   (3.072 MHz bit clock, generated by PIO)
 *   PCM1808 LRCK       → GPIO 3   (48 kHz L/R clock, generated by PIO)
 *   PCM1808 DOUT       → GPIO 4   (I2S data to Pico)
 *   PCM1808 MD0        → GND      (slave mode)
 *   PCM1808 MD1        → GND      (slave mode)
 *   PCM1808 FMT        → 3.3V     (left-justified format, matches this PIO driver)
 *   PCM1808 VINL       → TL072 SOUT (guitar signal, AC-coupled)
 *   PCM1808 VINR       → GND or NC
 */

#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/dma.h"
#include "hardware/clocks.h"
#include "hardware/resets.h"
#include "i2s_in.pio.h"

#include <cstdio>
#include <cmath>

// ---------------------------------------------------------------------------
// GPIO assignments
// ---------------------------------------------------------------------------
#define I2S_IN_BCK_PIN   2    // BCK output; LRCK = BCK_PIN + 1 = GPIO 3
#define I2S_IN_DATA_PIN  4    // DOUT input from PCM1808
#define SCKI_PIN         21   // 12.288 MHz system clock to PCM1808 (GPOUT0)

// ---------------------------------------------------------------------------
// Audio parameters
// 1 second × 2 channels × 4 bytes = 384 KB — fits in RP2350's 520 KB SRAM.
// ---------------------------------------------------------------------------
static constexpr uint32_t SAMPLE_RATE     = 48000;
static constexpr uint32_t CAPTURE_SAMPLES = SAMPLE_RATE;   // 1 second

// Stereo int32 capture buffer: L word, R word, L word, R word, ...
static int32_t stereo_buf[CAPTURE_SAMPLES * 2];

// ---------------------------------------------------------------------------
// Raw byte UART output (avoids newline translation on binary WAV data)
// ---------------------------------------------------------------------------
static void write_bytes(const void *buf, uint32_t len) {
    const uint8_t *p = static_cast<const uint8_t *>(buf);
    for (uint32_t i = 0; i < len; i++) putchar_raw(p[i]);
}
static void write_u16_le(uint16_t v) {
    uint8_t b[2] = { uint8_t(v), uint8_t(v >> 8) };
    write_bytes(b, 2);
}
static void write_u32_le(uint32_t v) {
    uint8_t b[4] = { uint8_t(v), uint8_t(v>>8), uint8_t(v>>16), uint8_t(v>>24) };
    write_bytes(b, 4);
}

// ---------------------------------------------------------------------------

int main() {
    stdio_init_all();

    // Wait for host ready signal (same handshake as capture_wav.py)
    while (true) {
        printf("READY\n");
        fflush(stdout);
        int c = getchar_timeout_us(1000000);
        if (c != PICO_ERROR_TIMEOUT) break;
    }

    printf("PCM1808 test — capturing 1 sec @ %u Hz\n", SAMPLE_RATE);
    fflush(stdout);

    // ---- Reset DMA and PIO1 to clear any stale bootrom USB stack state ----
    reset_block(RESETS_RESET_DMA_BITS | RESETS_RESET_PIO1_BITS);
    unreset_block_wait(RESETS_RESET_DMA_BITS | RESETS_RESET_PIO1_BITS);

    // ---- SCKI: route sys_clk / 12.207 ≈ 12.288 MHz to GPIO 21 (GPOUT0) ----
    // 150 MHz / 12.207 ≈ 12.288 MHz = 256 × 48 kHz (PCM1808 auto-detects 256fs)
    clock_gpio_init(SCKI_PIN, CLOCKS_CLK_GPOUT0_CTRL_AUXSRC_VALUE_CLK_SYS, 12.207f);

    // ---- PIO I2S input (pio1 SM0 — pio0 SM0 is used by main firmware output) ----
    PIO  pio    = pio1;
    uint sm     = 0;
    uint offset = pio_add_program(pio, &i2s_in_program);

    pio_sm_config c = i2s_in_program_get_default_config(offset);
    sm_config_set_in_pins(&c, I2S_IN_DATA_PIN);
    sm_config_set_sideset_pins(&c, I2S_IN_BCK_PIN);
    sm_config_set_in_shift(&c, false, true, 32);  // shift left, autopush at 32 bits
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);

    // PIO clock = 2 × BCK = 2 × (48000 × 64) = 6.144 MHz
    float div = (float)clock_get_hz(clk_sys) / (2.0f * SAMPLE_RATE * 64.0f);
    sm_config_set_clkdiv(&c, div);

    pio_gpio_init(pio, I2S_IN_BCK_PIN);
    pio_gpio_init(pio, I2S_IN_BCK_PIN + 1);
    pio_gpio_init(pio, I2S_IN_DATA_PIN);
    pio_sm_set_consecutive_pindirs(pio, sm, I2S_IN_BCK_PIN,  2, true);   // BCK+LRCK out
    pio_sm_set_consecutive_pindirs(pio, sm, I2S_IN_DATA_PIN, 1, false);  // DOUT in

    pio_sm_init(pio, sm, offset + i2s_in_offset_entry_point, &c);

    // ---- DMA: PIO RX FIFO → stereo_buf (single transfer, no ping-pong) ----
    int dma_chan = dma_claim_unused_channel(true);
    dma_channel_config dc = dma_channel_get_default_config(dma_chan);
    channel_config_set_transfer_data_size(&dc, DMA_SIZE_32);
    channel_config_set_read_increment(&dc, false);
    channel_config_set_write_increment(&dc, true);
    channel_config_set_dreq(&dc, pio_get_dreq(pio, sm, false));
    dma_channel_configure(dma_chan, &dc,
        stereo_buf, &pio->rxf[sm], CAPTURE_SAMPLES * 2, false);

    // ---- Capture 1 second to RAM ----// Let the PIO run for 500 ms before capturing so the AC coupling cap between
    // TL072 SOUT and PCM1808 VINL can charge to its steady-state bias point.
    // Without this, the first ~0.5 s of every capture is silence.
    pio_sm_set_enabled(pio, sm, true);
    sleep_ms(500);
    while (!pio_sm_is_rx_fifo_empty(pio, sm)) pio_sm_get(pio, sm);  // drain stale FIFO

    printf("Capturing — strum now!\n");
    fflush(stdout);

    uint64_t t0 = time_us_64();
    dma_channel_start(dma_chan);
    dma_channel_wait_for_finish_blocking(dma_chan);
    uint64_t capture_ms = (time_us_64() - t0) / 1000;
    pio_sm_set_enabled(pio, sm, false);

    printf("Done. Capture took %llu ms. Streaming WAV (~8 sec at 115200 baud)...\n", capture_ms);
    fflush(stdout);

    // ---- Stream WAV header ----
    // PIO ISR shift-left: stereo_buf[2i]=left word, stereo_buf[2i+1]=right word.
    // Each word: bit[31..8] = 24-bit audio (MSB first), bit[7..0] = zero padding.
    // To 16-bit: (int32_t)word >> 8 = signed 24-bit; >> 8 again = 16-bit.
    const uint32_t data_bytes = CAPTURE_SAMPLES * sizeof(int16_t);

    printf("WAV_DATA_START\n");
    fflush(stdout);

    write_bytes("RIFF", 4);
    write_u32_le(36 + data_bytes);
    write_bytes("WAVE", 4);
    write_bytes("fmt ", 4);
    write_u32_le(16);
    write_u16_le(1);                    // PCM
    write_u16_le(1);                    // mono
    write_u32_le(SAMPLE_RATE);
    write_u32_le(SAMPLE_RATE * 2);      // byte rate
    write_u16_le(2);                    // block align
    write_u16_le(16);                   // bits per sample
    write_bytes("data", 4);
    write_u32_le(data_bytes);

    // ---- Stream left channel as 16-bit PCM, compute stats inline ----
    int32_t  peak   = 0;
    int64_t  sum_sq = 0;

    for (uint32_t i = 0; i < CAPTURE_SAMPLES; i++) {
        int32_t s24 = stereo_buf[i * 2] >> 8;
        int16_t s16 = static_cast<int16_t>(s24 >> 8);
        uint8_t b[2] = { uint8_t(s16 & 0xFF), uint8_t((s16 >> 8) & 0xFF) };
        write_bytes(b, 2);
        int32_t a = s24 < 0 ? -s24 : s24;
        if (a > peak) peak = a;
        sum_sq += static_cast<int64_t>(s16) * s16;
    }

    printf("\nWAV_DATA_END\n");
    float rms = sqrtf((float)sum_sq / CAPTURE_SAMPLES);
    printf("Peak: %ld  RMS: %.1f  (16-bit scale)\n", (long)peak, rms);
    if (rms < 50.0f)
        printf("WARNING: very low signal — check connections and gain setting\n");
    else
        printf("Signal detected OK\n");
    fflush(stdout);

    while (true) tight_loop_contents();
}