#!/usr/bin/env python3
"""
Pre-build step: convert WAV files in audio/samples/ into C/binary forms for the firmware.

Outputs:
  audio/samples/ir_array.h     — IR as a static const float[] C header
  audio/samples/piezo_raw.bin  — piezo samples as raw float32 LE binary (no WAV header)
                                  embedded in the firmware image via objcopy

Usage (called automatically by CMake, or manually):
  python3 tools/gen_audio_arrays.py <samples_dir>
"""

import struct
import sys
import os


def read_wav_mono_float(path):
    """Read a WAV file (PCM int or IEEE float, any channel count) and return
    (samples: list[float], sample_rate: int) mixed down to mono."""
    with open(path, 'rb') as f:
        if f.read(4) != b'RIFF':
            raise ValueError(f"Not a RIFF file: {path}")
        f.read(4)  # file size
        if f.read(4) != b'WAVE':
            raise ValueError(f"Not a WAVE file: {path}")

        audio_fmt = channels = sr = bits = None

        while True:
            chunk_id = f.read(4)
            if len(chunk_id) < 4:
                break
            chunk_size = struct.unpack('<I', f.read(4))[0]

            if chunk_id == b'fmt ':
                data = f.read(min(chunk_size, 16))
                audio_fmt, channels, sr, _, _, bits = struct.unpack('<HHIIHH', data)
                if chunk_size > 16:
                    f.seek(chunk_size - 16, 1)

            elif chunk_id == b'data':
                raw = f.read(chunk_size)
                bps = bits // 8
                n = chunk_size // (bps * channels)
                samples = []

                for i in range(n):
                    ch_vals = []
                    for ch in range(channels):
                        offset = i * bps * channels + ch * bps
                        b = raw[offset:offset + bps]

                        if audio_fmt == 3 and bits == 32:
                            v = struct.unpack('<f', b)[0]
                        elif bits == 16:
                            v = struct.unpack('<h', b)[0] / 32768.0
                        elif bits == 24:
                            v = int.from_bytes(b, 'little', signed=True) / 8388608.0
                        elif bits == 32 and audio_fmt == 1:
                            v = struct.unpack('<i', b)[0] / 2147483648.0
                        else:
                            v = 0.0
                        ch_vals.append(v)

                    samples.append(sum(ch_vals) / len(ch_vals))

                return samples, sr

            else:
                f.seek(chunk_size, 1)  # skip unknown chunks (fact, PEAK, etc.)

    raise ValueError(f"No data chunk found in {path}")


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <samples_dir>", file=sys.stderr)
        sys.exit(1)

    samples_dir = sys.argv[1]

    ir_wav    = os.path.join(samples_dir, 'IR_garrison-NT1-A-20260320_48k_2048_M.wav')
    piezo_wav = os.path.join(samples_dir, 'garrison-piezo-20260320.wav')
    ir_out    = os.path.join(samples_dir, 'ir_array.h')
    piezo_out = os.path.join(samples_dir, 'piezo_raw.bin')

    # ---- IR → C float array header ----
    print(f"Reading IR: {ir_wav}")
    ir_samples, ir_rate = read_wav_mono_float(ir_wav)
    print(f"  {len(ir_samples)} samples @ {ir_rate} Hz")

    with open(ir_out, 'w') as f:
        f.write("// Auto-generated by tools/gen_audio_arrays.py — do not edit\n")
        f.write("#pragma once\n")
        f.write(f"static const uint32_t ir_sample_rate = {ir_rate}u;\n")
        f.write(f"static const uint32_t ir_num_samples  = {len(ir_samples)}u;\n")
        f.write(f"static const float    ir_samples[{len(ir_samples)}] = {{\n")
        for i, s in enumerate(ir_samples):
            if i % 8 == 0:
                f.write("    ")
            f.write(f"{s:.8f}f")
            if i < len(ir_samples) - 1:
                f.write(", ")
            if (i + 1) % 8 == 0:
                f.write("\n")
        if len(ir_samples) % 8 != 0:
            f.write("\n")
        f.write("};\n")
    print(f"  Written: {ir_out}")

    # ---- Piezo → raw float32 binary ----
    print(f"Reading piezo: {piezo_wav}")
    piezo_samples, piezo_rate = read_wav_mono_float(piezo_wav)
    print(f"  {len(piezo_samples)} samples @ {piezo_rate} Hz  ({len(piezo_samples)/piezo_rate:.2f} sec)")

    if ir_rate != piezo_rate:
        print(f"  WARNING: IR sample rate ({ir_rate}) != piezo sample rate ({piezo_rate})")
        print(f"  The convolution result will have pitch/timing artefacts.")

    packed = struct.pack(f'<{len(piezo_samples)}f', *piezo_samples)
    with open(piezo_out, 'wb') as f:
        f.write(packed)
    print(f"  Written: {piezo_out}  ({len(packed)} bytes)")


if __name__ == '__main__':
    main()
